import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bhuvnesh Verma | Full-Stack Developer & System Architect",
  icons: {
    icon: "/icon.jpeg",
  },
  description:
    "Bhuvnesh Verma — Full-stack developer specializing in scalable SaaS platforms, cloud-native infrastructure, and enterprise-grade applications. B.Tech AI & ML student at RCOEM, Nagpur. Building production-ready software with Node.js, React, Expo, AWS, and DevOps.",
  keywords: [
    "Bhuvnesh Verma",
    "full-stack developer",
    "software engineer",
    "system architect",
    "SaaS developer",
    "Node.js",
    "React",
    "Next.js",
    "Expo",
    "React Native",
    "TypeScript",
    "AWS",
    "DevOps",
    "Docker",
    "Kubernetes",
    "Terraform",
    "PostgreSQL",
    "Redis",
    "cloud-native",
    "CI/CD",
    "infrastructure as code",
    "RAG pipelines",
    "AI agents",
    "LangChain",
    "GDG RBU",
    "RCOEM Nagpur",
    "AI and ML",
    "Studzee",
    "Skarm",
    "WCL Examination Platform",
    "portfolio",
  ],
  authors: [{ name: "Bhuvnesh Verma" }],
  creator: "Bhuvnesh Verma",
  openGraph: {
    title: "Bhuvnesh Verma | Full-Stack Developer & System Architect",
    description:
      "Full-stack developer building scalable, production-ready software and enterprise-grade applications. Expertise in Node.js, React, AWS, DevOps, and cloud-native architecture.",
    type: "website",
    locale: "en_US",
    siteName: "Bhuvnesh Verma Portfolio",
  },
  twitter: {
    card: "summary_large_image",
    title: "Bhuvnesh Verma | Full-Stack Developer & System Architect",
    description:
      "Full-stack developer building scalable, production-ready software and enterprise-grade applications. Expertise in Node.js, React, AWS, DevOps, and cloud-native architecture.",
  },
  robots: "index, follow",
};
